-- Script generated by Redgate Compare v1.2.2.6772

SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping test_schema_github.table1';END$$;
DROP TABLE test_schema_github.table1;
SET check_function_bodies = true;
