-- Script generated by Redgate Compare v1.2.2.6772

SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping test_schema_github.view1';END$$;
DROP VIEW test_schema_github.view1;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping test_schema_github.add1(integer, integer)';END$$;
DROP FUNCTION test_schema_github.add1(integer, integer);
SET check_function_bodies = true;
