-- Script generated by Redgate Compare v1.2.2.7048

SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping test_schema_github.table4';END$$;
DROP TABLE test_schema_github.table4;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping test_schema_github.func1(integer)';END$$;
DROP FUNCTION test_schema_github.func1(integer);
SET check_function_bodies = true;
