-- Script generated by Redgate Compare v1.2.2.6772

SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating test_schema_github.table2...';END$$;
CREATE TABLE test_schema_github.table2 (
    id integer
);
SET check_function_bodies = true;
