-- Script generated by Redgate Compare v1.2.2.7048

SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating test_schema_github.table4...';END$$;
CREATE TABLE test_schema_github.table4 (
    id integer,
    name character varying(50)
);


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating test_schema_github.func1(integer)...';END$$;
CREATE FUNCTION test_schema_github.func1(IN integer)
RETURNS integer
LANGUAGE sql
AS $_$ select $1 + 1; $_$;
SET check_function_bodies = true;
